<img src="ku_logo_uk_v.png" alt="drawing" width="130" style="float:right"/>

# <span style="color:#2c061f"> Week 10 </span>  

<br>

## <span style="color:#374045"> Introduction to Programming and Numerical Analysis </span>


####  <span style="color:#d89216"> <br> Simon Guldager </span>

## Plan for today
<br>

1. Data project
2. Linear algebra and equations in Python!
3. Problem set 6

# 1. Data project feedback
Feedback for your project will again be via email.  
I will start going through your projects this week (the data project takes longer, as everyone have done something different).  

- Make sure everyone in your group is able to run the code after they've pulled, and after "Restart Kernel and Run All Cells"
- Paths that work on your own computer don't work on mine "PATH ON YOUR COMPUER/data/ xxx.csv, having "data/ xxx.csv" is fine - relative path

# 2. Linear algebra in Python:

We want to solve:

$$Ax = B$$

In [2]:
import numpy as np # import numpy
from scipy import linalg # import linalg

np.random.seed(666) # set seed

A = np.random.uniform(size=(5,5)) # draw random A matrix
B = np.random.uniform(size=5) # draw random B vector

print(f'Matrix A: \n{A} \n\n Matrix b:\n{B}')

Matrix A: 
[[0.70043712 0.84418664 0.67651434 0.72785806 0.95145796]
 [0.0127032  0.4135877  0.04881279 0.09992856 0.50806631]
 [0.20024754 0.74415417 0.192892   0.70084475 0.29322811]
 [0.77447945 0.00510884 0.11285765 0.11095367 0.24766823]
 [0.0232363  0.72732115 0.34003494 0.19750316 0.90917959]] 

 Matrix b:
[0.97834699 0.53280254 0.25913185 0.58381262 0.32569065]


## First way to solve (easier but slower)

In [3]:
# Simple solver
x = linalg.solve(A,B)
x

array([-1.09856672, -5.64094348, -3.17432935,  5.50035431,  4.89126724])

## Faster way to solve (code is a bit more complicated)

In [4]:
LU, piv = linalg.lu_factor(A) # compute LU decomposition of A
x = linalg.lu_solve((LU,piv),B) # solve equation system
x

array([-1.09856672, -5.64094348, -3.17432935,  5.50035431,  4.89126724])

# 2. Equations in Python
Formulas and models are part of the life as an economist. `Sympy` enables us to translate these formulas into python code.

Consider a utility function from a standard OLG model. Economic agents live two periods (young/old) and obtain utility from consumption in both periods:

$$U(c_{1}, c_{2}) = u(c_{1}) + \frac{1}{1+\rho}u(c_{2})$$

In [1]:
import sympy as sm # import sympy

c1,c2 = sm.symbols("c_1"), sm.symbols("c_2") # define C_i1 and C_i2
rho = sm.symbols("rho") # define rho

#log-utility
uc1 = sm.ln(c1) 
uc2 = sm.ln(c2)
# Define U_it
U = uc1+1/(1+rho)*uc2
U

log(c_1) + log(c_2)/(rho + 1)

Let's take the derivative of $U$ with respect to $c_2$

In [6]:
sm.diff(U,c2)

1/(c_2*(rho + 1))

# Formulas can be turned into python functions

We use `lambdify` to turn an expression into a Python function.  
Here "U" is an expression of sybmols, this enables us to treat it like any other function, turning the symbols into arguments:

In [7]:
util = sm.lambdify((c1,c2,rho),U)
util(5, 5, 0.5)

2.6823965207235005