In [34]:
import numpy as np 
from scipy import linalg
np.random.seed(2021)
A = np.random.uniform(size=(5,5))
b = np.random.uniform(size=5)
print(f'Matrix A: \n{A} \n\n Matrix b:\n{b}')

Matrix A: 
[[0.60597828 0.73336936 0.13894716 0.31267308 0.99724328]
 [0.12816238 0.17899311 0.75292543 0.66216051 0.78431013]
 [0.0968944  0.05857129 0.96239599 0.61655744 0.08662996]
 [0.56127236 0.61652471 0.96384302 0.57430429 0.37116085]
 [0.45214524 0.20185025 0.56930512 0.19509597 0.58370402]] 

 Matrix b:
[0.47631347 0.5178144  0.82309863 0.73222503 0.06905627]


# Model Project
Link to code examples: https://github.com/Goldfield1/NumEconClass

## What is the goal of the project? (from ModelProject.pdf)
<img src="req.PNG" style="float:center" width="800">

## Idea of how to structure your project (you don't **have** to follow this)

- Present a model (write a bit of text about the model and it's use)
- Present the analytical solution (this is a nice way of checking whether your numerical method is correct)
    - However, this should only take up a small part of your project
- Solve the model numerically
- Solve the model again with other parameters (**this is important**) 
    - Maybe use widgets to switch between different parameter values
- Solve the model with an extension numerically
- Describe an algoritm from lecture 10 (if you have time)

## Useful Python tools

In [28]:
import numpy as np
from scipy import optimize
import sympy as sm
from sympy import Symbol
from sympy.solvers import solve

For the analytical solution, `sympy` is nice

In [12]:
x = sm.symbols('x') 
y = sm.symbols('y') 
eq = sm.Eq(2*x**3 - y, 0) # y^2 + x^2 = 0

sm.solve(eq, (x,y))

[(x, 2*x**3)]

Finding a FOC?

In [20]:
x = sm.symbols('x') 
y = sm.symbols('y') 
f = (x - 3)**2
f

(x - 3)**2

In [25]:
ff = sm.diff(f)

In [27]:
sm.solve(sm.Eq(ff, 0), x)

[3]

Numerical solution, you will probably use `scipy.optimize` (for functions with multiple variables) and `scipy.optimize_scalar` for functions with only one

In [43]:
# example with two variables
def obj(x): # x is a vector
    return x[0]**(1/3) * 0.5*x[1] - x[0], x[1]**(1/3) * x[0] - 0.3*x[1]

sol = optimize.root(obj, [1,1])
sol.x

array([0.26305966, 0.82110651])

# Some ideas

DO NOTE: You are not allowed to use the basic Solow Model! (since it has already been covered at the lectures)

- OLG-model
    - Possibe extensions: Government debt, many periods
- Ramsey-model
- Cournot or Bertrand competition
- Solow model with an extension, human capital, endogenous technological growth, limited resources 

# Examples of project
In the "model project" folder: https://github.com/Goldfield1/NumEconClass  

Three examples of projects from previous (please don't copy 1:1 or I will get in trouble, but feel free to get inspired)
- Solow model with human capital
- Cournot model
- Solow model with Malthusian population limits